require('core.builtin.globals')
require('core.builtin.keys')
require('core.builtin.options')
require('core.builtin.event')

require('core.builtin.stl').setup()
require('core.builtin.lsp')
require('core.builtin.message')
require('keymap')
require('utils')
