local quickrun = require('utils.quickrun')
local flip_word = require('utils.flip-word')
local swap = require('utils.treesitter.swap')
local select = require('utils.treesitter.select')
require('utils.stl').setup()
require('utils.terminal')

vim.keymap.set('n', 'ts', swap.act)
vim.keymap.set({ 'x', 'o' }, 'if', function()
  select.act('function', false)
end)
vim.keymap.set({ 'x', 'o' }, 'af', function()
  select.act('function', true)
end)
vim.keymap.set({ 'x', 'o' }, 'ic', function()
  select.act('class', false)
end)
vim.keymap.set({ 'x', 'o' }, 'ac', function()
  select.act('class', true)
end)
vim.keymap.set({ 'x', 'o' }, 'il', function()
  select.act('loop', false)
end)
vim.keymap.set({ 'x', 'o' }, 'al', function()
  select.act('loop', true)
end)

vim.keymap.set('n', '<leader>r', quickrun.run)
vim.keymap.set('n', 'ta', flip_word.toggle)

vim.keymap.set({ 'n', 't' }, '<A-i>', function()
  _G.Terms.toggle()
end)
